---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[why-run-alerting::default]
    attributes: {
    	loggly_username: <%= ENV['LOGGLY_USERNAME'] %>,
      loggly_appname: <%= ENV['LOGGLY_APPNAME'] %>,
      loggly_access_key: <%= ENV['LOGGLY_KEY'] %>
    }
